export const ELEMENTS = {
    urlHome: 'https://www.petz.com.br/',
    acceptLGPD: '#aceiteLgpd',
    componentLogin: '.greetings',
    createAccount: 'Criar conta',
    urlRegister: 'https://www.petz.com.br/novo_ClienteLoja.html',
    physicalPerson: '#tipoPessoaFisica',
    legalPerson: '#tipoPessoaJuridica',
    name: '#Nome',
    email: '#Email',
    dddCel: '[name="cliente.dddCelular"]',
    numberCel: '[name="cliente.celular"]',
    dddTel: '#DDD',
    numberTel: '#Telefone',
    sexo: '#Sexo',
    birthDate: '#dataNascimento',
    CPF: '#CPF-CNPJ',
    password: '#Senha',
    confirmPassword: '#confirmasenha',
    showPass: '#showPass',
    showPass2: '#showPass2',
    buttonCreateNewAccount: '#criarContaButton',
    closeModalSuccess: 'Entendi',
    buttonLogin: 'Entrar',
    createAccountLogin: 'Criar minha conta' 
}