export const ELEMENTS = {
    urlDog: 'https://www.petz.com.br/cachorro',
    categoryDog: '[href="/cachorro"]:first',
    idProduct: '[data-idproduto="71353"]',
    addCart: '#adicionarAoCarrinho',
    continueCart: 'Continuar',
    cep: '#cep-input',
    address: '#rua',
    numberAddress: '#numero',
    district: '#bairro',
    state: '#estado',
    city: '#cidade',
    nameAddress: '#apelido',
    continueCheckout: '#continuarEndereco',
    finishOrder: 'Conclua seu pedido',
    urlProduct: 'https://www.petz.com.br/produto/racao-golden-formula-senior-para-caes-adultos-sabor-frango-e-arroz-15kg-71353',
    urlCart : 'https://www.petz.com.br/comprarAgora_Loja.html',
    cepCart: '#carrinhoCep',
    buttonFreight: '.btn-frete',
    choosePickup: '#pickupStoreId',
    normalDelivery: '#entregaNormal',
    componentAddress: ':nth-child(2) > .reset-margin > .boxes',
    componentPayment: '.box-pagamento > .reset-margin > .boxes'

}